export default {
    service: 'FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFF0',
    startRecord: 'FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFF1',
    stopRecord: 'FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFF2',
    logMetaData: 'FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFF3',
    stream: 'FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFF4',
    read: 'FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFF5',
};
